name: Daily Annotator Report

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current date
        run: echo "CURRENT_DAY=$(date '+%A, %d %B %Y')" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Decode and write SSH private key
        run: |
          mkdir -p secrets
          echo "${{ secrets.ENCORD_PRIVATE_KEY_B64 }}" | base64 -d > secrets/encord-alejandra-accelerate-private-key.ed25519
          chmod 600 secrets/encord-alejandra-accelerate-private-key.ed25519

      - name: Run script
        run: python scheduled_tasks/annotator_acuracy.py

      - name: Send email with CSV
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Annotator Accuracy Report - ${{ env.CURRENT_DAY }}"
          body: |
            Hi team,

            Attached is the latest Annotator Accuracy report. 
            The statistics reflect all-time annotation performance for the project Yutori - Aug 11 Delivery "fb5c3af6-f023-4f70-87da-29bc7d4ac658"
            
            Accuracy is calculated as: 
            Accuracy = # approvals / ( # approvals + # rejections )

            Best regards,
            Alejandra 
            
            Automated Reporting System
          to: ${{ secrets.REPORT_EMAIL }}
          from: ${{ secrets.FROM_EMAIL }}
          attachments: "*.csv"
