name: Post Daily Quality Review to Slack
on:
  schedule:
    - cron: '30 16 * * *'  # 5:30 PM London time (during DST)
  workflow_dispatch:     # Allows manual runs from the GitHub UI

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Decode and write SSH private key
        run: |
          mkdir -p secrets
          echo "${{ secrets.ENCORD_PRIVATE_KEY_B64 }}" | base64 -d > secrets/encord-alejandra-accelerate-private-key.ed25519
          chmod 600 secrets/encord-alejandra-accelerate-private-key.ed25519

      - name: Run accuracy script
        run: python scheduled_tasks/identify_underperforming_annotators.py

      - name: Generate daily quality report
        id: script
        run: |
          OUTPUT=$(python identify_underperforming_annotators.py)
          echo "payload=$OUTPUT" >> $GITHUB_OUTPUT

      - name: Send quality report to Slack
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: ${{ steps.script.outputs.payload }}
